### ISSUE TITLE
Project without LICENSE file

### ISSUE THREAD

**Issue by ismtabo** [Peque/PyConES-Spain-2018-eureka#1]
I am the guy you talk with in the workshop at the PyCon Es. I asked you about the possibility of using your notebook in other talks at the university, and you asked me to remind you that it hasn't got a license. 

Here is your remainder.

**Comment by Peque** [comment]
Thanks for the reminder! :blush:

Here is the license: https://github.com/Peque/PyConES-Spain-2018-eureka/blob/master/LICENSE
